### ISSUE TITLE
document restrictions on composer.action

### ISSUE THREAD

**Issue by dgrove-oss** [ibm-functions/composer#45]
The documentation suggests that maybe this could work:
```
function prepareDocument(args) { ... }
composer.sequence(...,
  composer.action('prepareDocument', { action : prepareDocument }), .... )

```

However, it fails at runtime with
```
   "response": {
        "status": "application error",
        "statusCode": 0,
        "success": false,
        "result": {
            "error": "Initialization has failed due to: ReferenceError: main is not defined\n    at eval (eval at <anonymous> (/nodejsAction/runner.js:76:109), <anonymous>:14:8)\n    at eval (eval at <anonymous> (/nodejsAction/runner.js:76:109), <anonymous>:14:14)\n    at NodeActionRunner.init (/nodejsAction/runner.js:76:45)\n    at doInit (/nodejsAction/src/service.js:134:31)\n    at initCode (/nodejsAction/src/service.js:82:24)\n    at /nodejsAction/app.js:61:13\n    at Layer.handle [as handle_request] (/nodejsAction/node_modules/express/lib/router/layer.js:95:5)\n    at next (/nodejsAction/node_modules/express/lib/router/route.js:131:13)\n    at Route.dispatch (/nodejsAction/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/nodejsAction/node_modules/express/lib/router/layer.js:95:5)"
        }
    },

```

**Comment by dgrove-oss** [comment]
The correct code is
```
function prepareDocument(args) { ... }
composer.sequence(...,
  composer.function(prepareDocument), .... )

```

**Comment by tardieu** [comment]
@dgrove-oss This should work now. Could you test and confirm?
